apiVersion: apps/v1

kind: Deployment

metadata:

  name: todo-django-deployment

  labels:

    app: todo-django-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: todo-django-app

  template:

    metadata:

      labels:

        app: todo-django-app

    spec:

      containers:

      - name: todo-django-app

        image: public.ecr.aws/q4o3m7g1/todo-djangoapp:latest

        ports:

        - containerPort: 8005

