apiVersion: apps/v1

kind: Deployment

metadata:

  name: tododjango-deployment

  labels:

    app: todotododjango-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: todotododjango-app

  template:

    metadata:

      labels:

        app: todotododjango-app

    spec:

      containers:

      - name: todotododjango-app

        image: chetana249/todoapp:latest

        ports:

        - containerPort: 8000

